- id: rubocop
  name: Check Ruby style with rubocop
  description: Enforce Ruby style guide with rubocop
  entry: bin/rubocop-wrapper.sh
  language: script
  pass_filenames: true
  types: ['ruby']
- id: erblint
  name: Check erb file style with erblint
  description: Enforce ERB style guide with erblint
  entry: bin/erblint-wrapper.sh
  language: script
  pass_filenames: true
  types: ['erb']
